/* =============================================================
   NGE Reporting / Data-Warehouse layer — schemas (PostgreSQL)
   -------------------------------------------------------------
   PostgreSQL port of sql/reporting/00_schemas.sql. Four schemas:
     dw       dimensional model (dimensions, line-grain facts,
              wide OBT) — the materialised reporting DATA.
     rpt      READ-ONLY analytical procs/functions over dw + OLTP.
     batch    reprocessable (idempotent) ETL procedures that READ
              OLTP and WRITE dw.
     loadgen  workload/chaos procedures the load generator calls.

   Contract: OLTP (dbo/hr/web/finance) is READ-ONLY; writes are
   confined to dw. The DW is DERIVED and REPROCESSABLE. Idempotent.

   Type conventions match schema_v1_postgres.sql:
     BIT->BOOLEAN  NVARCHAR(n)->VARCHAR(n)  TINYINT->SMALLINT
     DATETIME2(3)->TIMESTAMP(3)  IDENTITY->GENERATED BY DEFAULT
     no COLLATE (Postgres default, case-sensitive)
   Columnstore has no Postgres equivalent: sales_wide is a plain
   heap and the fact/rollup columnstore indexes are replaced by
   BRIN (on occurred_at) + covering btrees, built by the ETL.
   ============================================================= */

CREATE SCHEMA IF NOT EXISTS dw;
CREATE SCHEMA IF NOT EXISTS rpt;
CREATE SCHEMA IF NOT EXISTS batch;
CREATE SCHEMA IF NOT EXISTS loadgen;

/* Batch bookkeeping — every refresh procedure writes one row here so runs are
   auditable and reprocessing is traceable (start/end/rows/status). */
CREATE TABLE IF NOT EXISTS dw.etl_run_log (
    run_id        BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proc_name     VARCHAR(128)  NOT NULL,
    target_object VARCHAR(128)  NULL,
    mode          VARCHAR(16)   NOT NULL,            -- 'full' | 'incremental'
    started_at    TIMESTAMP(3)  NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
    finished_at   TIMESTAMP(3)  NULL,
    rows_affected BIGINT        NULL,
    status        VARCHAR(16)   NOT NULL DEFAULT 'running',  -- 'running'|'ok'|'error'
    message       VARCHAR(2000) NULL
);
